In [2]:
import numpy as np
import pandas as pd

In [6]:
data = pd.read_csv('Pass-Fail Data.csv')
data.head()

student_id  attendance_pct  homework_pct  midterm_score  \
0           1              95            92             88   
1           2              88            85             79   
2           3              60            55             58   
3           4              72            70             65   
4           5              40            45             50   

   study_hours_per_week  pass  
0                    12     1  
1                    10     1  
2                     4     0  
3                     6     1  
4                     3     0

In [7]:
study = data["study_hours_per_week"].values
study

array([12, 10,  4,  6,  3, 14,  8,  5, 11,  6,  2,  9,  7,  4, 15,  5, 10,
        3, 12,  7,  4,  9,  2,  8, 11,  5,  3, 10,  6,  4, 12,  9,  4,  7,
        3, 14,  8,  5, 11,  6,  2,  9,  7,  4, 15,  5, 10,  3, 12,  7,  4,
        9,  2,  8, 11,  5,  3, 10,  6,  4, 13, 10,  4,  7,  3, 14,  8,  5,
       11,  6,  2,  9,  8,  4, 15,  5, 10,  3, 12,  7,  4,  9,  2,  8, 11,
        5,  3, 10,  6,  4, 13, 10,  4,  7,  3, 14,  8,  5, 12,  4])

In [12]:
midterm = data['midterm_score'].values
midterm

array([88, 79, 58, 65, 50, 91, 74, 62, 84, 60, 42, 76, 68, 55, 93, 59, 82,
       52, 86, 66, 57, 78, 48, 70, 85, 58, 50, 80, 63, 54, 87, 79, 56, 69,
       49, 92, 75, 60, 83, 64, 45, 77, 70, 53, 95, 60, 84, 54, 85, 67, 58,
       79, 47, 71, 86, 59, 51, 81, 64, 55, 89, 82, 57, 69, 50, 93, 76, 59,
       85, 65, 44, 78, 72, 52, 97, 61, 85, 55, 87, 68, 56, 80, 46, 73, 88,
       58, 49, 83, 65, 55, 90, 81, 56, 70, 48, 94, 75, 58, 88, 53])

In [ ]:
np.mean(study)
np.median(midterm)
np.std(midterm)


np.float64(14.64348319219167)

In [ ]:
np.max(midterm)
np.min(midterm)
np.sort(midterm)


array([42, 44, 45, 46, 47, 48, 48, 49, 49, 50, 50, 50, 51, 52, 52, 53, 53,
       54, 54, 55, 55, 55, 55, 56, 56, 56, 57, 57, 58, 58, 58, 58, 58, 59,
       59, 59, 60, 60, 60, 61, 62, 63, 64, 64, 65, 65, 65, 66, 67, 68, 68,
       69, 69, 70, 70, 70, 71, 72, 73, 74, 75, 75, 76, 76, 77, 78, 78, 79,
       79, 79, 80, 80, 81, 81, 82, 82, 83, 83, 84, 84, 85, 85, 85, 85, 86,
       86, 87, 87, 88, 88, 88, 89, 90, 91, 92, 93, 93, 94, 95, 97])

In [23]:
np.sort(midterm[-5:])


array([53, 58, 75, 88, 94])

In [26]:
data['Performance'] = (data['attendance_pct']*0.3 + 
                       data['homework_pct']*0.3 + 
                       data['midterm_score']*0.4)
data

student_id  attendance_pct  homework_pct  midterm_score  \
0            1              95            92             88   
1            2              88            85             79   
2            3              60            55             58   
3            4              72            70             65   
4            5              40            45             50   
..         ...             ...           ...            ...   
95          96              89            92             94   
96          97              79            77             75   
97          98              55            56             58   
98          99              91            90             88   
99         100              52            50             53   

    study_hours_per_week  pass  Performance  
0                     12     1         91.3  
1                     10     1         83.5  
2                      4     0         57.7  
3                      6     1         68.6  
4                      3     0         45.5  
..                   ...   ...          ...  
95                    14     1         91.9  
96                     8     1         76.8  
97                     5     0         56.5  
98                    12     1         89.5  
99                     4     0         51.8  

[100 rows x 7 columns]

In [29]:
data['Hard_working'] = data['study_hours_per_week']>10
data

student_id  attendance_pct  homework_pct  midterm_score  \
0            1              95            92             88   
1            2              88            85             79   
2            3              60            55             58   
3            4              72            70             65   
4            5              40            45             50   
..         ...             ...           ...            ...   
95          96              89            92             94   
96          97              79            77             75   
97          98              55            56             58   
98          99              91            90             88   
99         100              52            50             53   

    study_hours_per_week  pass  Performance  Hard_working  
0                     12     1         91.3          True  
1                     10     1         83.5         False  
2                      4     0         57.7         False  
3                      6     1         68.6         False  
4                      3     0         45.5         False  
..                   ...   ...          ...           ...  
95                    14     1         91.9          True  
96                     8     1         76.8         False  
97                     5     0         56.5         False  
98                    12     1         89.5          True  
99                     4     0         51.8         False  

[100 rows x 8 columns]

In [31]:
data.to_csv('Output_data.csv',index = False)